### ISSUE TITLE
swagger content type image/svg+xml does not resond

### ISSUE THREAD

**Issue by physikerwelt** [ag-gipp/vmext#10]
Originally reported by: **Moritz Schubotz (Bitbucket: [physikerwelt](https://bitbucket.org/physikerwelt), GitHub: [physikerwelt](https://github.com/physikerwelt))**

----------------------------------------

![bitbucketSucks.png](https://bitbucket.org/repo/gE4a75/images/2893926727-bitbucketSucks.png)

----------------------------------------
- Bitbucket: https://bitbucket.org/sciplore/htw-citeplag-node/issue/10

**Comment by agilc** [comment]
> +xml

Where can I edit this ? I am using swagger-ui NPM module.
