### ISSUE TITLE
Internal error on "identical" comparison ("similar" works fine)

### ISSUE THREAD

**Issue by vstange** [ag-gipp/vmext#12]
An internal error during an "identical" comparison occurred. Whereby if I try it as a "similar" comparison everything works fine. The example is quite easy: compare a+b against b+c. The corresponding MathML and similarities are as follows:

`<math xmlns="http://www.w3.org/1998/Math/MathML" id="p1.1.m1.1" class="ltx_Math" alttext="a+b" display="inline">
  <semantics id="p1.1.m1.1a">
    <mrow id="p1.1.m1.1.4" xref="p1.1.m1.1.4.cmml">
      <mi id="p1.1.m1.1.1" xref="p1.1.m1.1.1.cmml">a</mi>
      <mo id="p1.1.m1.1.2" xref="p1.1.m1.1.2.cmml">+</mo>
      <mi id="p1.1.m1.1.3" xref="p1.1.m1.1.3.cmml">b</mi>
    </mrow>
    <annotation-xml encoding="MathML-Content" id="p1.1.m1.1b">
      <apply id="p1.1.m1.1.4.cmml" xref="p1.1.m1.1.4">
        <plus id="p1.1.m1.1.2.cmml" xref="p1.1.m1.1.2"/>
        <ci id="p1.1.m1.1.1.cmml" xref="p1.1.m1.1.1">𝑎</ci>
        <ci id="p1.1.m1.1.3.cmml" xref="p1.1.m1.1.3">𝑏</ci>
      </apply>
    </annotation-xml>
  </semantics>
</math>`

`<math xmlns="http://www.w3.org/1998/Math/MathML" id="p1.1.m1.1" class="ltx_Math" alttext="b+a" display="inline">
  <semantics id="p1.1.m1.1a">
    <mrow id="p1.1.m1.1.4" xref="p1.1.m1.1.4.cmml">
      <mi id="p1.1.m1.1.1" xref="p1.1.m1.1.1.cmml">b</mi>
      <mo id="p1.1.m1.1.2" xref="p1.1.m1.1.2.cmml">+</mo>
      <mi id="p1.1.m1.1.3" xref="p1.1.m1.1.3.cmml">a</mi>
    </mrow>
    <annotation-xml encoding="MathML-Content" id="p1.1.m1.1b">
      <apply id="p1.1.m1.1.4.cmml" xref="p1.1.m1.1.4">
        <plus id="p1.1.m1.1.2.cmml" xref="p1.1.m1.1.2"/>
        <ci id="p1.1.m1.1.1.cmml" xref="p1.1.m1.1.1">𝑏</ci>
        <ci id="p1.1.m1.1.3.cmml" xref="p1.1.m1.1.3">𝑎</ci>
      </apply>
    </annotation-xml>
  </semantics>
</math>`

`[
  {
    "id": "p1.1.m1.1.4.cmml",
    "matches": [
      {
        "id": "p1.1.m1.1.4.cmml",
        "assessment": 1,
        "type": "identical"
      }
    ]
  }
]`

If I now change the similarity **type** to "similar" it works just fine. Why?

**Comment by LuiSlacker** [comment]
This occurs for the edge case when identical match is root of tree. The incoming edges are undefined and cannot be removed.
