### ISSUE TITLE
Missing node in a Merged AST

### ISSUE THREAD

**Issue by vstange** [ag-gipp/vmext#13]
In the demo we use this comparison as an example:

`<math xmlns="http://www.w3.org/1998/Math/MathML" id="p1.1.m1.1" class="ltx_Math" alttext="\EulerGamma@{z}=\Int{0}{\infty}@{t}{e^{-t}t^{z-1}}" display="inline">
  <semantics id="p1.1.m1.1a">
    <mrow id="p1.1.m1.1.4" xref="p1.1.m1.1.4.cmml">
      <mrow id="p1.1.m1.1.1.8.2" xref="p1.1.m1.1.1.1.cmml">
        <mpadded width="-1.7pt" id="p1.1.m1.1.1.2" xref="p1.1.m1.1.1.1.cmml">
          <mi mathvariant="normal" id="p1.1.m1.1.1.2.1.2" xref="p1.1.m1.1.1.2.1.1.cmml">Γ</mi>
        </mpadded>
        <mo id="p1.1.m1.1.1.8.2a" xref="p1.1.m1.1.1.1.cmml">⁡</mo>
        <mrow id="p1.1.m1.1.1.8.2.1" xref="p1.1.m1.1.1.1.cmml">
          <mo id="p1.1.m1.1.1.5" xref="p1.1.m1.1.1.1.cmml">(</mo>
          <mi id="p1.1.m1.1.1.6" xref="p1.1.m1.1.1.6.cmml">z</mi>
          <mo id="p1.1.m1.1.1.7" xref="p1.1.m1.1.1.1.cmml">)</mo>
        </mrow>
      </mrow>
      <mo id="p1.1.m1.1.2" xref="p1.1.m1.1.2.cmml">=</mo>
      <mrow id="p1.1.m1.1.3.8" xref="p1.1.m1.1.3.1.cmml">
        <msubsup id="p1.1.m1.1.3.2.1.6" xref="p1.1.m1.1.3.2.1.1.cmml">
          <mo largeop="true" symmetric="true" id="p1.1.m1.1.3.2.1.2" xref="p1.1.m1.1.3.2.1.1.1.cmml">∫</mo>
          <mn id="p1.1.m1.1.3.2.1.3.1" xref="p1.1.m1.1.3.2.1.3.1.cmml">0</mn>
          <mi mathvariant="normal" id="p1.1.m1.1.3.2.1.4.1" xref="p1.1.m1.1.3.2.1.4.1.cmml">∞</mi>
        </msubsup>
        <mo id="p1.1.m1.1.3.8a" xref="p1.1.m1.1.3.1.cmml">⁡</mo>
        <mrow id="p1.1.m1.1.3.8.1" xref="p1.1.m1.1.3.1.cmml">
          <mpadded width="+1.7pt" id="p1.1.m1.1.3.4" xref="p1.1.m1.1.3.4.cmml">
            <mrow id="p1.1.m1.1.3.4a" xref="p1.1.m1.1.3.4.cmml">
              <msup id="p1.1.m1.1.3.4.6" xref="p1.1.m1.1.3.4.6.cmml">
                <mi id="p1.1.m1.1.3.4.1" xref="p1.1.m1.1.3.4.1.cmml">e</mi>
                <mrow id="p1.1.m1.1.3.4.2.1" xref="p1.1.m1.1.3.4.2.1.cmml">
                  <mo id="p1.1.m1.1.3.4.2.1.1" xref="p1.1.m1.1.3.4.2.1.1.cmml">-</mo>
                  <mi id="p1.1.m1.1.3.4.2.1.2" xref="p1.1.m1.1.3.4.2.1.2.cmml">t</mi>
                </mrow>
              </msup>
              <mo id="p1.1.m1.1.3.4.5" xref="p1.1.m1.1.3.4.5.cmml">⁢</mo>
              <msup id="p1.1.m1.1.3.4.7" xref="p1.1.m1.1.3.4.7.cmml">
                <mi id="p1.1.m1.1.3.4.3" xref="p1.1.m1.1.3.4.3.cmml">t</mi>
                <mrow id="p1.1.m1.1.3.4.4.1" xref="p1.1.m1.1.3.4.4.1.cmml">
                  <mi id="p1.1.m1.1.3.4.4.1.1" xref="p1.1.m1.1.3.4.4.1.1.cmml">z</mi>
                  <mo id="p1.1.m1.1.3.4.4.1.2" xref="p1.1.m1.1.3.4.4.1.2.cmml">-</mo>
                  <mn id="p1.1.m1.1.3.4.4.1.3" xref="p1.1.m1.1.3.4.4.1.3.cmml">1</mn>
                </mrow>
              </msup>
            </mrow>
          </mpadded>
          <mo id="p1.1.m1.1.3.8.1.1" xref="p1.1.m1.1.3.1.cmml">⁢</mo>
          <mi mathvariant="normal" id="p1.1.m1.1.3.6" xref="p1.1.m1.1.3.1.cmml">d</mi>
          <mo id="p1.1.m1.1.3.8.1.1a" xref="p1.1.m1.1.3.1.cmml">⁢</mo>
          <mi id="p1.1.m1.1.3.7" xref="p1.1.m1.1.3.7.cmml">t</mi>
        </mrow>
      </mrow>
    </mrow>
    <annotation-xml encoding="MathML-Content" id="p1.1.m1.1b">
      <apply id="p1.1.m1.1.4.cmml" xref="p1.1.m1.1.4">
        <eq id="p1.1.m1.1.2.cmml" xref="p1.1.m1.1.2"/>
        <apply id="p1.1.m1.1.1.1.cmml" xref="p1.1.m1.1.1.8.2">
          <csymbol cd="dlmf" id="p1.1.m1.1.1.2.1.1.cmml" xref="p1.1.m1.1.1.2.1.2">Euler-Gamma</csymbol>
          <ci id="p1.1.m1.1.1.6.cmml" xref="p1.1.m1.1.1.6">𝑧</ci>
        </apply>
        <apply id="p1.1.m1.1.3.1.cmml" xref="p1.1.m1.1.3.8">
          <apply id="p1.1.m1.1.3.2.1.1.cmml" xref="p1.1.m1.1.3.2.1.6">
            <csymbol cd="dlmf" id="p1.1.m1.1.3.2.1.1.1.cmml" xref="p1.1.m1.1.3.2.1.2">semantic-definite-integral</csymbol>
            <cn type="integer" id="p1.1.m1.1.3.2.1.3.1.cmml" xref="p1.1.m1.1.3.2.1.3.1">0</cn>
            <infinity id="p1.1.m1.1.3.2.1.4.1.cmml" xref="p1.1.m1.1.3.2.1.4.1"/>
          </apply>
          <ci id="p1.1.m1.1.3.7.cmml" xref="p1.1.m1.1.3.7">𝑡</ci>
          <apply id="p1.1.m1.1.3.4.cmml" xref="p1.1.m1.1.3.4">
            <times id="p1.1.m1.1.3.4.5.cmml" xref="p1.1.m1.1.3.4.5"/>
            <apply id="p1.1.m1.1.3.4.6.cmml" xref="p1.1.m1.1.3.4.6">
              <power xmlns:m="http://www.w3.org/1998/Math/MathML" xref="p1.1.m1.1.3.4.6"/>
              <ci id="p1.1.m1.1.3.4.1.cmml" xref="p1.1.m1.1.3.4.1">𝑒</ci>
              <apply id="p1.1.m1.1.3.4.2.1.cmml" xref="p1.1.m1.1.3.4.2.1">
                <minus id="p1.1.m1.1.3.4.2.1.1.cmml" xref="p1.1.m1.1.3.4.2.1.1"/>
                <ci id="p1.1.m1.1.3.4.2.1.2.cmml" xref="p1.1.m1.1.3.4.2.1.2">𝑡</ci>
              </apply>
            </apply>
            <apply id="p1.1.m1.1.3.4.7.cmml" xref="p1.1.m1.1.3.4.7">
              <power xmlns:m="http://www.w3.org/1998/Math/MathML" xref="p1.1.m1.1.3.4.7"/>
              <ci id="p1.1.m1.1.3.4.3.cmml" xref="p1.1.m1.1.3.4.3">𝑡</ci>
              <apply id="p1.1.m1.1.3.4.4.1.cmml" xref="p1.1.m1.1.3.4.4.1">
                <minus id="p1.1.m1.1.3.4.4.1.2.cmml" xref="p1.1.m1.1.3.4.4.1.2"/>
                <ci id="p1.1.m1.1.3.4.4.1.1.cmml" xref="p1.1.m1.1.3.4.4.1.1">𝑧</ci>
                <cn type="integer" id="p1.1.m1.1.3.4.4.1.3.cmml" xref="p1.1.m1.1.3.4.4.1.3">1</cn>
              </apply>
            </apply>
          </apply>
        </apply>
      </apply>
    </annotation-xml>
  </semantics>
</math>`

`<math xmlns="http://www.w3.org/1998/Math/MathML" id="p1.1.m1.1" class="ltx_Math" alttext="\EulerGamma@{z}=\Int{0}{\infty}@{x}{e^{-x}t^{z-1}}" display="inline">
  <semantics id="p1.1.m1.1a">
    <mrow id="p1.1.m1.1.4" xref="p1.1.m1.1.4.cmml">
      <mrow id="p1.1.m1.1.1.8.2" xref="p1.1.m1.1.1.1.cmml">
        <mpadded width="-1.7pt" id="p1.1.m1.1.1.2" xref="p1.1.m1.1.1.1.cmml">
          <mi mathvariant="normal" id="p1.1.m1.1.1.2.1.2" xref="p1.1.m1.1.1.2.1.1.cmml">Γ</mi>
        </mpadded>
        <mo id="p1.1.m1.1.1.8.2a" xref="p1.1.m1.1.1.1.cmml">⁡</mo>
        <mrow id="p1.1.m1.1.1.8.2.1" xref="p1.1.m1.1.1.1.cmml">
          <mo id="p1.1.m1.1.1.5" xref="p1.1.m1.1.1.1.cmml">(</mo>
          <mi id="p1.1.m1.1.1.6" xref="p1.1.m1.1.1.6.cmml">z</mi>
          <mo id="p1.1.m1.1.1.7" xref="p1.1.m1.1.1.1.cmml">)</mo>
        </mrow>
      </mrow>
      <mo id="p1.1.m1.1.2" xref="p1.1.m1.1.2.cmml">=</mo>
      <mrow id="p1.1.m1.1.3.8" xref="p1.1.m1.1.3.1.cmml">
        <msubsup id="p1.1.m1.1.3.2.1.6" xref="p1.1.m1.1.3.2.1.1.cmml">
          <mo largeop="true" symmetric="true" id="p1.1.m1.1.3.2.1.2" xref="p1.1.m1.1.3.2.1.1.1.cmml">∫</mo>
          <mn id="p1.1.m1.1.3.2.1.3.1" xref="p1.1.m1.1.3.2.1.3.1.cmml">0</mn>
          <mi mathvariant="normal" id="p1.1.m1.1.3.2.1.4.1" xref="p1.1.m1.1.3.2.1.4.1.cmml">∞</mi>
        </msubsup>
        <mo id="p1.1.m1.1.3.8a" xref="p1.1.m1.1.3.1.cmml">⁡</mo>
        <mrow id="p1.1.m1.1.3.8.1" xref="p1.1.m1.1.3.1.cmml">
          <mpadded width="+1.7pt" id="p1.1.m1.1.3.4" xref="p1.1.m1.1.3.4.cmml">
            <mrow id="p1.1.m1.1.3.4a" xref="p1.1.m1.1.3.4.cmml">
              <msup id="p1.1.m1.1.3.4.6" xref="p1.1.m1.1.3.4.6.cmml">
                <mi id="p1.1.m1.1.3.4.1" xref="p1.1.m1.1.3.4.1.cmml">e</mi>
                <mrow id="p1.1.m1.1.3.4.2.1" xref="p1.1.m1.1.3.4.2.1.cmml">
                  <mo id="p1.1.m1.1.3.4.2.1.1" xref="p1.1.m1.1.3.4.2.1.1.cmml">-</mo>
                  <mi id="p1.1.m1.1.3.4.2.1.2" xref="p1.1.m1.1.3.4.2.1.2.cmml">x</mi>
                </mrow>
              </msup>
              <mo id="p1.1.m1.1.3.4.5" xref="p1.1.m1.1.3.4.5.cmml">⁢</mo>
              <msup id="p1.1.m1.1.3.4.7" xref="p1.1.m1.1.3.4.7.cmml">
                <mi id="p1.1.m1.1.3.4.3" xref="p1.1.m1.1.3.4.3.cmml">t</mi>
                <mrow id="p1.1.m1.1.3.4.4.1" xref="p1.1.m1.1.3.4.4.1.cmml">
                  <mi id="p1.1.m1.1.3.4.4.1.1" xref="p1.1.m1.1.3.4.4.1.1.cmml">z</mi>
                  <mo id="p1.1.m1.1.3.4.4.1.2" xref="p1.1.m1.1.3.4.4.1.2.cmml">-</mo>
                  <mn id="p1.1.m1.1.3.4.4.1.3" xref="p1.1.m1.1.3.4.4.1.3.cmml">1</mn>
                </mrow>
              </msup>
            </mrow>
          </mpadded>
          <mo id="p1.1.m1.1.3.8.1.1" xref="p1.1.m1.1.3.1.cmml">⁢</mo>
          <mi mathvariant="normal" id="p1.1.m1.1.3.6" xref="p1.1.m1.1.3.1.cmml">d</mi>
          <mo id="p1.1.m1.1.3.8.1.1a" xref="p1.1.m1.1.3.1.cmml">⁢</mo>
          <mi id="p1.1.m1.1.3.7" xref="p1.1.m1.1.3.7.cmml">x</mi>
        </mrow>
      </mrow>
    </mrow>
    <annotation-xml encoding="MathML-Content" id="p1.1.m1.1b">
      <apply id="p1.1.m1.1.4.cmml" xref="p1.1.m1.1.4">
        <eq id="p1.1.m1.1.2.cmml" xref="p1.1.m1.1.2"/>
        <apply id="p1.1.m1.1.1.1.cmml" xref="p1.1.m1.1.1.8.2">
          <csymbol cd="dlmf" id="p1.1.m1.1.1.2.1.1.cmml" xref="p1.1.m1.1.1.2.1.2">Euler-Gamma</csymbol>
          <ci id="p1.1.m1.1.1.6.cmml" xref="p1.1.m1.1.1.6">𝑧</ci>
        </apply>
        <apply id="p1.1.m1.1.3.1.cmml" xref="p1.1.m1.1.3.8">
          <apply id="p1.1.m1.1.3.2.1.1.cmml" xref="p1.1.m1.1.3.2.1.6">
            <csymbol cd="dlmf" id="p1.1.m1.1.3.2.1.1.1.cmml" xref="p1.1.m1.1.3.2.1.2">semantic-definite-integral</csymbol>
            <cn type="integer" id="p1.1.m1.1.3.2.1.3.1.cmml" xref="p1.1.m1.1.3.2.1.3.1">0</cn>
            <infinity id="p1.1.m1.1.3.2.1.4.1.cmml" xref="p1.1.m1.1.3.2.1.4.1"/>
          </apply>
          <ci id="p1.1.m1.1.3.7.cmml" xref="p1.1.m1.1.3.7">𝑥</ci>
          <apply id="p1.1.m1.1.3.4.cmml" xref="p1.1.m1.1.3.4">
            <times id="p1.1.m1.1.3.4.5.cmml" xref="p1.1.m1.1.3.4.5"/>
            <apply id="p1.1.m1.1.3.4.6.cmml" xref="p1.1.m1.1.3.4.6">
              <power xmlns:m="http://www.w3.org/1998/Math/MathML" xref="p1.1.m1.1.3.4.6"/>
              <ci id="p1.1.m1.1.3.4.1.cmml" xref="p1.1.m1.1.3.4.1">𝑒</ci>
              <apply id="p1.1.m1.1.3.4.2.1.cmml" xref="p1.1.m1.1.3.4.2.1">
                <minus id="p1.1.m1.1.3.4.2.1.1.cmml" xref="p1.1.m1.1.3.4.2.1.1"/>
                <ci id="p1.1.m1.1.3.4.2.1.2.cmml" xref="p1.1.m1.1.3.4.2.1.2">𝑥</ci>
              </apply>
            </apply>
            <apply id="p1.1.m1.1.3.4.7.cmml" xref="p1.1.m1.1.3.4.7">
              <power xmlns:m="http://www.w3.org/1998/Math/MathML" xref="p1.1.m1.1.3.4.7"/>
              <ci id="p1.1.m1.1.3.4.3.cmml" xref="p1.1.m1.1.3.4.3">𝑡</ci>
              <apply id="p1.1.m1.1.3.4.4.1.cmml" xref="p1.1.m1.1.3.4.4.1">
                <minus id="p1.1.m1.1.3.4.4.1.2.cmml" xref="p1.1.m1.1.3.4.4.1.2"/>
                <ci id="p1.1.m1.1.3.4.4.1.1.cmml" xref="p1.1.m1.1.3.4.4.1.1">𝑧</ci>
                <cn type="integer" id="p1.1.m1.1.3.4.4.1.3.cmml" xref="p1.1.m1.1.3.4.4.1.3">1</cn>
              </apply>
            </apply>
          </apply>
        </apply>
      </apply>
    </annotation-xml>
  </semantics>
</math>`

`[
  {
    "id": "p1.1.m1.1.1.1.cmml",
    "matches": [
      {
        "id": "p1.1.m1.1.1.1.cmml",
        "assessment": 1,
        "type": "identical"
      }
    ]
  },
  {
    "id": "p1.1.m1.1.3.7.cmml",
    "matches": [
      {
        "id": "p1.1.m1.1.3.4.3.cmml",
        "assessment": 1,
        "type": "identical"
      }
    ]
  },
  {
    "id": "p1.1.m1.1.3.4.1.cmml",
    "matches": [
      {
        "id": "p1.1.m1.1.3.4.1.cmml",
        "assessment": 1,
        "type": "identical"
      }
    ]
  },
  {
    "id": "p1.1.m1.1.3.4.2.1.2.cmml",
    "matches": [
      {
        "id": "p1.1.m1.1.3.4.3.cmml",
        "assessment": 1,
        "type": "identical"
      }
    ]
  },
  {
    "id": "p1.1.m1.1.3.4.7.cmml",
    "matches": [
      {
        "id": "p1.1.m1.1.3.4.7.cmml",
        "assessment": 1,
        "type": "identical"
      }
    ]
  }
]`

The bound variable t from the left integral is missing.

**Comment by physikerwelt** [comment]
![2017-03-28](https://cloud.githubusercontent.com/assets/2777736/24667991/dcced3e6-1997-11e7-9659-72d5bf5a0dc3.png)
@nmeuschke the t is missing here ;-)

**Comment by physikerwelt** [comment]
@LuiSlacker @skaufhold do you have a guess, what might cause this problem?

**Comment by physikerwelt** [comment]
In the server console I see the following error:
Can not create edge `5f5ff4bb-5642-4c9b-bf8a-6965e4381044` with nonexistant source `A.p1.1.m1.1.3.4.2.1.2.cmml`

**Comment by LuiSlacker** [comment]
The server throws:
 **Can not create edge `be2076e5-4219-42c8-8796-37bbc0529def` with nonexistant source `A.p1.1.m1.1.3.4.2.1.2.cmml`**

This is due to the fact that the 2nd factor (t^z-1) within both integrals is marked identical and therefore being collapsed. Now additionally the similarities-json states another identical match for differental dt (formula 1) towards the base of already collapsed power (t^z-1) within formula 2.

As far as I'm aware of, we currently don't support multiple matches to identical nodes. 
The same applies for the fifth match listed in similarities-json (exponent -t formuala 1 towards - base of collapsed power (t^z-1))


See similarities-json without multiple matches to the same nodes. (removed 2nd & 4th match from original json)
```
[
   {
      "id":"p1.1.m1.1.1.1.cmml",
      "matches":[
         {
            "id":"p1.1.m1.1.1.1.cmml",
            "assessment":1,
            "type":"identical"
         }
      ]
   },
   {
      "id":"p1.1.m1.1.3.4.1.cmml",
      "matches":[
         {
            "id":"p1.1.m1.1.3.4.1.cmml",
            "assessment":1,
            "type":"identical"
         }
      ]
   },
   {
      "id":"p1.1.m1.1.3.4.7.cmml",
      "matches":[
         {
            "id":"p1.1.m1.1.3.4.7.cmml",
            "assessment":1,
            "type":"identical"
         }
      ]
   }
]

```

**Comment by physikerwelt** [comment]
^^ that was a quick response. I could not even type that fast.

**Comment by vstange** [comment]
If only the 2th match is removed everything seems fine, even thought the the 4th match still points to a collapsed node in formula 2.
Nevertheless I would expect: when a match points to a collapsed node its okay to receive an error but it should not stop the other node from rendering.
