### ISSUE TITLE
mathoid returns undefined for riemann-example

### ISSUE THREAD

**Issue by LuiSlacker** [ag-gipp/vmext#14]
mathoid API returns undefined for Riemann example of simple AST widget.
Since mathoid seems to be accessible only within uni konstanz cluster, it's also hard to debug vmext  locally (outside cluster), since mathoid has to be replaced by mathjax-node in order to work.

<img width="859" alt="screen shot 2017-04-07 at 11 09 53" src="https://cloud.githubusercontent.com/assets/6152940/24794379/aafd146e-1b85-11e7-9979-d26d9d42c267.png">

**Comment by physikerwelt** [comment]
Yes. I need to improve the stability of the remote server. But that is another issue.
