### ISSUE TITLE
Error on rendering for multiple matches on the same node

### ISSUE THREAD

**Issue by vstange** [ag-gipp/vmext#17]
A small example is `x+x` and `x+1` and we have two matches for `x` between these formulas. Currently this can not be rendered and instead a response 500 internal server error is given. Is this a direct conclusion from the explanations in issue #13?

`<math xmlns="http://www.w3.org/1998/Math/MathML" id="p1.1.m1.1" class="ltx_Math" alttext="x+x" display="inline">
  <semantics id="p1.1.m1.1a">
    <mrow id="p1.1.m1.1.4" xref="p1.1.m1.1.4.cmml">
      <mi id="p1.1.m1.1.1" xref="p1.1.m1.1.1.cmml">x</mi>
      <mo id="p1.1.m1.1.2" xref="p1.1.m1.1.2.cmml">+</mo>
      <mi id="p1.1.m1.1.3" xref="p1.1.m1.1.3.cmml">x</mi>
    </mrow>
    <annotation-xml encoding="MathML-Content" id="p1.1.m1.1b">
      <apply id="p1.1.m1.1.4.cmml" xref="p1.1.m1.1.4">
        <plus id="p1.1.m1.1.2.cmml" xref="p1.1.m1.1.2"/>
        <ci id="p1.1.m1.1.1.cmml" xref="p1.1.m1.1.1">𝑥</ci>
        <ci id="p1.1.m1.1.3.cmml" xref="p1.1.m1.1.3">𝑥</ci>
      </apply>
    </annotation-xml>
  </semantics>
</math>`  

`<math xmlns="http://www.w3.org/1998/Math/MathML" id="p1.1.m1.1" class="ltx_Math" alttext="x+1" display="inline">
  <semantics id="p1.1.m1.1a">
    <mrow id="p1.1.m1.1.4" xref="p1.1.m1.1.4.cmml">
      <mi id="p1.1.m1.1.1" xref="p1.1.m1.1.1.cmml">x</mi>
      <mo id="p1.1.m1.1.2" xref="p1.1.m1.1.2.cmml">+</mo>
      <mn id="p1.1.m1.1.3" xref="p1.1.m1.1.3.cmml">1</mn>
    </mrow>
    <annotation-xml encoding="MathML-Content" id="p1.1.m1.1b">
      <apply id="p1.1.m1.1.4.cmml" xref="p1.1.m1.1.4">
        <plus id="p1.1.m1.1.2.cmml" xref="p1.1.m1.1.2"/>
        <ci id="p1.1.m1.1.1.cmml" xref="p1.1.m1.1.1">𝑥</ci>
        <cn type="integer" id="p1.1.m1.1.3.cmml" xref="p1.1.m1.1.3">1</cn>
      </apply>
    </annotation-xml>
  </semantics>
</math>`

`[
  {
    "id": "p1.1.m1.1.1.cmml",
    "matches": [
      {
        "id": "p1.1.m1.1.1.cmml",
        "assessment": 1,
        "type": "identical"
      }
    ]
  },
  {
    "id": "p1.1.m1.1.3.cmml",
    "matches": [
      {
        "id": "p1.1.m1.1.1.cmml",
        "assessment": 1,
        "type": "identical"
      }
    ]
  }
]`

**Comment by vstange** [comment]
Can someone label this as an enhancement?

**Comment by physikerwelt** [comment]
![Uploading Screenshot from 2018-02-21 13-30-42.png…]()

**Comment by vstange** [comment]
Nope everything alright, seems to be working fine in the meantime :).
