### ISSUE TITLE
Error rendering identical formulas with nodes in different order

### ISSUE THREAD

**Issue by vstange** [ag-gipp/vmext#18]
In the demo I currently consider "a+b" **identical** to "b+a". Should we fix this at the rendering level or should I disabled different ordering for plus and times?

You can try out this example at http://mast-demo.wmflabs.org/

**Comment by physikerwelt** [comment]
![screenshot from 2018-02-21 13-36-04](https://user-images.githubusercontent.com/2777736/36480326-3271d6b4-170c-11e8-9764-636440e3ec2a.png)

**Comment by jiaqizhao122** [comment]
How do I get to the website interface shown above, I get this 
![Uploading 微信图片_20231123160655.png…]()
 when I open  vmext-demo.wmflabs.org/

**Comment by jiaqizhao122** [comment]
How can I get to the website interface shown above, I get this when I open vmext-demo.wmflabs.org/
<img width="1120" alt="微信图片_20231123160655" src="https://github.com/gipplab/vmext/assets/103194053/583ce119-fe14-457b-9e41-fb1201a79aaa">
