### ISSUE TITLE
Parser should also recognize MathML-Presentation annotation

### ISSUE THREAD

**Issue by vstange** [ag-gipp/vmext#27]
When reviewing the Arvix results from Citeplag, it is noticeable that many formulas simply can not be read. At the moment only the following constellation is read:
```
<semantics>
  ... pmml
  <annotation-xml encoding="MathML-Content" ...>
    ... cmml
  </annotation>
</semantics>
```
VMEXT should also acknowledge the following constellation:
```
<semantics>
  ... cmml
  <annotation-xml encoding="MathML-Presentation" ...>
    ... pmml
  </annotation>
</semantics>
```

**Comment by physikerwelt** [comment]
arg why do we reinvent the same functionality over and again.

**Comment by physikerwelt** [comment]
please fix the tests

**Comment by physikerwelt** [comment]
any news here?

**Comment by vstange** [comment]
The Problem was rendering and we didn't want to change this in mathoid. As a workaround, we could implement a mechanism that swapped the cmml and pmml in the printout, or directly control the output of pmml and cmml.
Would that be something for MathMLTools - CMMLInfo object?

**Comment by physikerwelt** [comment]
I guess it's a problem deep in MathJax. Fixing that would require a lot of effort. We should only send the pmml portion to mathoid, this will also reduce the network usage so I think this approach would be superior.

**Comment by vstange** [comment]
@physikerwelt thanks for the changes
