### ISSUE TITLE
What should we do with math.citeplag.org?

### ISSUE THREAD

**Issue by vstange** [ag-gipp/vmext#29]
http://math.citeplag.org still has a version online from 03/2017. At the moment the citeplag frontend relies on this URL API. I would like to change this towards (https://vmext.wmflabs.org/).

But what should we do with math.citeplag.org?

* Keep a second separate server online (of course updated)
* redirect towards vmext.wmflabs
* close this url down
* leave it be

@AndreG-P @physikerwelt @nmeuschke what is preferred by you?

I would go for a redirect at the moment.

**Comment by physikerwelt** [comment]
@vstange redirect is ok. maybe use our own domain vmext.formulasearchengine.com which is more stable

**Comment by physikerwelt** [comment]
@vstange I think andre can't do the redirect. so I unassigned andre from the task.

**Comment by vstange** [comment]
Redirect is active for:
http://math.citeplag.org/? > https://vmext.formulasearchengine.com
https://math.citeplag.org/? > https://vmext.formulasearchengine.com

Small problem: it seems the wmflabs server will not allow redirects with a subpath or query attached, every request lands on the main page. As far as I can see this happens when we are rediected from formulasearchengine-domain to wmflabs-domain.

The citeplag frontend will use the https://vmext.wmflabs.org address directly.

**Comment by physikerwelt** [comment]
thank you great job

**Comment by AndreG-P** [comment]
This could produce some site effects. It destroys the AST rendering of vmext-demo. I just fixed it by using the vmext.wmflabs location now. (https://github.com/ag-gipp/vmext-demo/issues/18)
``` yaml
mast.url: https://vmext.wmflabs.org/
```
It works. But is this correct or should it be https://vmext.formulasearchengine.com?

**Comment by vstange** [comment]
@AndreG-P Like I mentioned, it seems the wmflabs server will not allow redirects with a subpath or query attached.
For example: if you call https://vmext.formulasearchengine.com/api-docs you will be redirected to https://vmext.wmflabs.org/ instead.
