### ISSUE TITLE
Cannot use Node LTS 8

### ISSUE THREAD

**Issue by AndreG-P** [ag-gipp/vmext#37]
Cannot install packages with node version 8.10.0. Probably npm (v. 5.6.1) is the problem. It cannot find correct versions of packages(such as librsvg) online. Try to solve this issue via travis first.

------------------------------------

DRMF-Beta information:
The service is currently running in a screen session (named \d.vmext) by physikerwelt. Type screen -r to login the session or 
```
 screen -ls 
 screen -X -S <screen-session-name> quit
```
To kill the session.

**Comment by physikerwelt** [comment]
It's ok to run it with node 6 for now. If you need to run it with node 8 please fix it by yourself. I will probably not find time in the foreseeable future to work on this, unless I need this for other reasons.
